backend:
  name: github # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: master # Branch to update
  repo: emontes/radioxalli # Repo for pushing new commits. Make sure to replace with your repo!

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: "Post"
    folder: "content"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.md"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha de Publicación", name: "date", widget: "datetime"}
      - {label: "Imagen de Portada", name: "cover", widget: "image"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Categoría", name: "category", widget: "string"}
      - {label: "Etiquetas", name: "tags", widget: "list"}
      - {label: "Cuerpo", name: "body", widget: "markdown"}
